spring:
  datasource:
    url: jdbc:mysql://192.168.142.128:3306/quartz?user=root&password=123456&useUnicode=true&characterEncoding=utf8&useSSL=FALSE&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver



